name: Ruby

on:
  push:
  pull_request:
  schedule:
    - cron: '35 6 * * *'
  workflow_dispatch:

jobs:
  ruby-versions:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 3.3

  build:
    needs: ruby-versions
    name: CI (${{ matrix.ruby }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-24.04, windows-latest ]

    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

    - id: build
      run: |
        bundle exec rake build
        sha256sum pkg/*
        echo "pkg=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      if: >-
        ${{
        github.event_name == 'push' &&
        startsWith(matrix.os, 'ubuntu') &&
        (matrix.ruby == needs.ruby-versions.outputs.latest)
        }}
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}-${{matrix.os}}
      if: steps.build.outputs.pkg
